Feature/event
sunflower-atelier/meshireach pull request #21
Opened 2019-08-01 11:39 UTC by tsubasa7777

飯イベントにユーザを登録(イベントに参加)するAPIと飯イベントの参加者のリストを返すAPIの実装

2019-09-27 06:08 UTC, gihachi requested changes
いくつか直す

2019-09-27 06:08 UTC, gihachi commented on api/events.go
> +		db.Where(&model.User{Model: gorm.Model{ID: userid}}).First(&user)
これ2回同じことしてる

2019-09-27 06:08 UTC, gihachi commented on api/events.go
> +func RegisterEvents(db *gorm.DB) gin.HandlerFunc {
参加登録なので, joinEventとかにした方が良さそう.
RegisterEventsだとevent自体の登録に見える

2019-09-27 06:08 UTC, gihachi commented on main.go
> +		authedGroup.POST("/events", api.RegisterEvents(db))
他のapiとの兼ね合いでpathは直したい

2019-09-27 07:00 UTC, gihachi commented on api/events.go
> +func GetAllAttendees(db *gorm.DB) gin.HandlerFunc {
modelのフィールド名がparticipantsだからparticipantsにしたい

2019-10-04 05:03 UTC, gihachi commented on api/events.go
> +func JoinEvents(db *gorm.DB) gin.HandlerFunc {
これ参加したい人とownerが友達同士かバリデーション必要?

2019-10-04 05:20 UTC, akky2501 commented on api/events.go
> +		if db.Model(&event).Association("Users").Find(&usercopy).Count() != 0 {
Where句にする修正が必要

2019-10-04 05:21 UTC, akky2501 commented on api/events.go
> +
イベントに参加する人とイベントのオーナーが友達かどうか確認する

2019-10-04 05:26 UTC, akky2501 commented on api/events.go
> +func JoinEvents(db *gorm.DB) gin.HandlerFunc {
必要だとおもう

2019-10-08 06:03 UTC, gihachi commented on api/events.go
> +			"friends":  result,
friendsじゃなくてparticipantsの方がよくね?

2019-10-08 06:32 UTC, gihachi approved these changes

2019-10-08 06:40 UTC, merged