Run linter at ci
sunflower-atelier/meshireach pull request #7
Opened 2019-07-02 07:21 UTC by YotaroSeki

# やったこと
- CIでLinterが走ってなかったので、走るように修正

2019-07-07 10:13 UTC, gihachi requested changes
これtestを消してるからcircleci通らなくなってる?

2019-07-07 10:27 UTC, gihachi commented on .circleci/config.yml
> -  test:
ここtest消してるからcircleciでtest通った判定でなくなってる?

2019-07-07 12:48 UTC, YotaroSeki commented on .circleci/config.yml
> -  test:
全体見てもらえばわかるけど、2つのジョブに分けようとしたけど上手くいかなかったから1つのジョブにまとめただけなので、今までの全部の処理とgolintを1回で走らせるようにしたよ

2019-07-07 12:57 UTC, gihachi commented on .circleci/config.yml
> -  test:
じゃあブランチ設定のテスト外して良いだけってこと ?

2019-07-07 12:58 UTC, YotaroSeki commented on .circleci/config.yml
> -  test:
あ、すまん外し忘れてた
お願いします🙇‍♀️

2019-07-07 12:59 UTC, gihachi approved these changes

2019-07-07 13:07 UTC, gihachi commented on .circleci/config.yml
> -  test:
外した

2019-07-07 13:09 UTC, gihachi commented on .circleci/config.yml
> +          command: golint main.go
これmain.goにしかかけてないのは他のファイルが怒られるから?
暫定的にmain.goだけなのかな?

2019-07-08 10:19 UTC, YotaroSeki commented on .circleci/config.yml
> +          command: golint main.go
とりあえずマスター以外のブランチでどこになんのファイル置いてあるのか分からなかったので、ファイル追加時に追加してね〜ってお気持ちです

2019-07-08 10:46 UTC, gihachi commented on .circleci/config.yml
> +          command: golint main.go
一応 `` golint ./...``で全部lintかけてくれるっぽい
今やると直す箇所多くてめんどいが

2019-07-16 06:22 UTC, gihachi commented
とりあえずmain.goだけ見るようにする.
あとでブランチを切って 全ファイルにgolintをかけて怒られないように変更する

2019-07-16 06:22 UTC, merged